"""Add end_date to bookings and remove secondary_email

Revision ID: 7ce03a8170ff
Revises: a3af5be1245f
Create Date: 2025-12-03 17:22:37.272556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce03a8170ff'
down_revision: Union[str, Sequence[str], None] = 'a3af5be1245f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('bookings', 'secondary_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('secondary_email', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'end_date')
    # ### end Alembic commands ###
