"""Add contact fields to bookings nullable

Revision ID: a3af5be1245f
Revises: d39c989afa89
Create Date: 2025-12-03 16:48:48.824145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3af5be1245f'
down_revision: Union[str, Sequence[str], None] = 'd39c989afa89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('contact_email', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('contact_phone', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('secondary_email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'secondary_email')
    op.drop_column('bookings', 'contact_phone')
    op.drop_column('bookings', 'contact_email')
    # ### end Alembic commands ###
